# Generated by Django 6.1 on 2026-08-16 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('registration', 'Registration'), ('football', 'Instant Football'), ('bottle', 'Spin the Bottle'), ('diamonds', 'Diamond top-up')], max_length=20)),
                ('country', models.CharField(choices=[('ghana', 'Ghana'), ('nigeria', 'Nigeria'), ('other', 'Other')], default='ghana', max_length=20)),
                ('amount', models.CharField(blank=True, max_length=40)),
                ('transaction_id', models.CharField(blank=True, max_length=80)),
                ('sender_name', models.CharField(max_length=120)),
                ('paid_from', models.CharField(max_length=80)),
                ('screenshot', models.ImageField(upload_to='payments/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending admin confirmation'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('football', 'Instant Football'), ('bottle', 'Spin the Bottle')], max_length=20)),
                ('cost', models.PositiveIntegerField(default=50)),
                ('payload', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('referral', models.CharField(blank=True, max_length=40)),
                ('registration_approved', models.BooleanField(default=False)),
                ('diamonds', models.PositiveIntegerField(default=0)),
                ('football_unlocked', models.BooleanField(default=False)),
                ('bottle_unlocked', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
